name: 'circular-dependency-detector'
description: 'Detect and output cycles and topological generations given a directed graph.'
inputs:
  adjacency_list_path:
    description: 'Path to a file where an adjacency list is stored'
    required: true
runs:
  using: "composite"
  steps:
    - name: Build Container
      run: |  
        docker build -t circular-dependency-detector --build-arg path=${{ inputs.adjacency_list_path }} .

    - name: Run Container
      run: |  
        docker run circular-dependency-detector
