name: 'circular-dependency-detector'
description: 'Detect and output cycles and topological generations given a directed graph.'
inputs:
  INPUT_PATH:
    description: 'absolute path to graph input file'
    required: true
  FAIL_ON_CYCLE:
    description: 'flag if action should fail if a cycle is detected'
    required: false
    default: true
  OUTPUT_FILE:
    description: 'absolute path to graph output file'
    required: false
    default: '/github/workspace'
  using: "docker"
  image: 'Dockerfile'
  # the order of these args matter to the internal running of the app
  args:
    - ${{ inputs.INPUT_PATH }}
    - ${{ inputs.FAIL_ON_CYCLE }}
    - ${{ inputs.OUTPUT_FILE }}
