version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  default:
    desc: display available tasks
    cmds:
      - task --list-all

  build:
    desc: build the container
    cmds:
      - docker build -t circular-dependency-detector .
    sources:
      - ./**/*.go
      - ./**/*.mod
      - ./**/*.sum
      - ./**/.env
      - ./entrypoint.sh
      - testing/**/*
      - Dockerfile
      - Taskfile.yml

  run:
    desc: run the program locally inside container
    deps: [build]
    cmds:
      - docker run circular-dependency-detector "{{ .INPUT_FILE }}" "{{ .FAIL_ON_CYCLE }}"

  test:
    desc: run the unit tests
    deps: [build]
    cmds:
      - docker run --entrypoint 'go' circular-dependency-detector test -v /app/...

  lint:
    desc: runs lint validation
    cmds:
      - golangci-lint run
    sources:
      - './**/*.go'
      - .golangci.yml

  # clean:
  #   cmds:
  #     - rm -rf .task/
