version: '3'

# env:
#   ENV: testing

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  build:
    cmds:
      - docker build -t circular-dependency-detector .
    sources:  # can this be shared?
      - ./**/*.go
      - ./**/*.mod
      - ./**/*.sum
      - ./**/.env
      - ./entrypoint.sh
      - testing/**/*

  run:
    deps: [build]
    cmds:
      - docker run circular-dependency-detector "{{ .INPUT_FILE }}"

  test:
    deps: [build]
    cmds:
      - docker run --entrypoint 'go' circular-dependency-detector test /app/...
