version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  default:
    desc: display available tasks
    cmds:
      - task --list-all

  build:
    desc: build the container
    cmds:
      - podman build -t circular-dependency-detector .
    sources:
      - ./**/*.go
      - ./**/*.mod
      - ./**/*.sum
      - ./**/.env
      - ./entrypoint.sh
      - testing/**/*
      - Dockerfile

  run:
    desc: run the program inside container
    deps: [build]
    cmds:
      - podman run circular-dependency-detector "{{ .INPUT_FILE }}"

  test:
    desc: run the unit tests
    deps: [build]
    cmds:
      - podman run --entrypoint 'go' circular-dependency-detector test -v /app/...

  lint:
    desc: runs lint validation
    sources:
      - './**/*.go'
      - .golangci.yml
    cmds:
      - golangci-lint run

  # clean:
  #   cmds:
  #     - rm -rf .task/
