version: '3'

# env:
#   ENV: testing

# dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  build:
    cmds:
      - docker build -t circular-dependency-detector .
    sources:
      - cmd/**/*.go
      - pkg/**/*.go
      - testing/**/*.go

  run:
    deps: [build]
    cmds:
      - docker run circular-dependency-detector

  test:
    deps: [build]
    cmds:
      - docker run --entrypoint 'go' circular-dependency-detector test /app/...
