version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  build:
    cmds:
      - docker build -t circular-dependency-detector .
    sources:
      - ./**/*.go
      - ./**/*.mod
      - ./**/*.sum
      - ./**/.env
      - ./entrypoint.sh
      - testing/**/*

  run:
    desc: run the program with a specific local input file based off config
    deps: [build]
    cmds:
      - docker run circular-dependency-detector "{{ .INPUT_FILE }}"

  test:
    desc: run the unit tests
    deps: [build]
    cmds:
      - docker run --entrypoint 'go' circular-dependency-detector test -v /app/...
