name: Pull Request Verification
on:
  pull_request:
    branches:
      - main

jobs:
  cdd-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        input_file:
          - adj_list_cycle.txt
          - adj_list_no_cycle.txt
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.GITHUB_REF_NAME }}  # current branch name
          path: './test/'

      - name: install task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: task run
        run: |
          cd  test/
          task INPUT_FILE="testing/data/${{ matrix.input_file }}" run
