name: Pull Request Verification
on:
  pull_request:
    branches:
      - main

jobs:
  cdd-e2e:
    runs-on: ubuntu-latest
    steps:
      # - name: circular-dependency-detector
      #   uses: tcm5343/circular-dependency-detector@main
      #   with:
      #     adjacency_list_path: /github/workspace/testing/data/some-input-graph.txt

      - name: checkout current branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.GITHUB_REF_NAME }}  # current branch name

      - name: install task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: run unit tests
        run: task test

      - name: create graph input file
        run: |
          echo -e "1 2\n2 3\n3 1" > /github/workspace/testing/data/some-input-graph.txt

      - name: task run
        run: |
          task INPUT_FILE="/app/testing/data/some-input-graph.txt" run
