name: Pull Request Verification
on:
  pull_request:
    branches:
      - main

jobs:
  circular-dependency-detector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.GITHUB_REF_NAME }}  # this should be current branch name
          path: './test/'

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Run branch specific circular dependency detector
        id: adj-list
        run: |
          cd  test/
          task INPUT_FILE="testing/adj_list_cycle.txt" test

      # - name: circular-dependency-detector
      #   uses: tcm5343/circular-dependency-detector@v0.1.0-alpha
      #   with:
      #     adjacency_list_path: ${{ steps.adj-list.outputs.adj-list-artifact-path }}
      
    # outputs:
    #   adj-list-artifact-path: ${{ steps.adj-list.outputs.adj-list-artifact-path }}

  # circular-dependency-detector:
  #   needs: build-adjacency-list
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         ref: miller-init

