name: Pull Request Verification
on:
  pull_request:
    branches:
      - main

jobs:
  cdd-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        input_file:
          - adj_list_cycle.txt
          # - adj_list_no_cycle.txt
    steps:
      - name: checkout current branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.GITHUB_REF_NAME }}  # current branch name
          path: './test/'

      - name: install task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: create graph input file
        run: |
          echo -e "1 2\n2 3\n3 1" > test.txt  && cat test/testing/data/test.txt

      - name: task run
        run: |
          cd  test/
          task INPUT_FILE="testing/data/test.txt" run
